apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-tls
  namespace: longhorn-system
spec:
  dnsNames:
    - longhorn.noosphere.uk
  issuerRef:
    kind: ClusterIssuer
    name: letnencrypt-cloudflare
  secretName: longhorn-tls
