apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: garage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: garage
    app.kubernetes.io/version: v2.1.0
    helm.sh/chart: garage-0.9.1
  name: allow-crds-for-garage-garage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manage-crds-garage-garage
subjects:
  - kind: ServiceAccount
    name: garage
    namespace: garage
