apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
  labels:
    app.kubernetes.io/instance: garage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: garage
    app.kubernetes.io/version: v2.1.0
    helm.sh/chart: garage-0.9.1
  name: garage-s3-api
  namespace: garage
spec:
  ingressClassName: traefik
  rules:
    - host: s3.garage.noosphere.uk
      http:
        paths:
          - backend:
              service:
                name: garage
                port:
                  number: 3900
            path: /
            pathType: Prefix
    - host: '*.s3.garage.noosphere.uk'
      http:
        paths:
          - backend:
              service:
                name: garage
                port:
                  number: 3900
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - s3.garage.noosphere.uk
        - '*.s3.garage.noosphere.uk'
      secretName: garage-tls
