apiVersion: v1
data:
  rpcSecret: OTY1NDQwYjY4MzI5MDQxYmE3MDUxY2I2MTY3NzI4OTIxNWUyODkyZGIzYTNlZTZkMTcyMzNlNGYxZjQ0MTdmYg==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: garage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: garage
    app.kubernetes.io/version: v2.1.0
    helm.sh/chart: garage-0.9.1
  name: garage-rpc-secret
  namespace: garage
type: Opaque
