apiVersion: v1
kind: Service
metadata:
  name: garage-admin
  namespace: garage
spec:
  ports:
    - name: admin
      port: 3903
      targetPort: 3903
  selector:
    app.kubernetes.io/instance: garage
    app.kubernetes.io/name: garage
  type: ClusterIP
