apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bytestash-tls
  namespace: bytestash
spec:
  dnsNames:
    - bytestash.noosphere.uk
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
  secretName: bytestash-tls
