apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: bytestash
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bytestash
    app.kubernetes.io/version: 1.5.7
    helm.sh/chart: bytestash-0.1.1
  name: bytestash
  namespace: bytestash
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: bytestash
      app.kubernetes.io/name: bytestash
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: bytestash
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: bytestash
        app.kubernetes.io/version: 1.5.7
        helm.sh/chart: bytestash-0.1.1
    spec:
      containers:
        - env:
            - name: BASE_PATH
              value: bytestash.noosphere.uk
            - name: DEBUG
              value: "false"
            - name: DISABLE_ACCOUNTS
              value: "false"
            - name: DISABLE_INTERNAL_ACCOUNTS
              value: "false"
            - name: ALLOW_NEW_ACCOUNTS
              value: "false"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwt-key
                  name: bytestash-jwt-secret
            - name: TOKEN_EXPIRY
              valueFrom:
                secretKeyRef:
                  key: expiry
                  name: bytestash-jwt-secret
          image: ghcr.io/jordan-dalby/bytestash:1.5.7
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: bytestash.noosphere.uk
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: bytestash
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: bytestash.noosphere.uk
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources: {}
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /data
              name: data
              subPath: snippets
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: default
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bytestash-data
