apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: bytestash
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bytestash
    app.kubernetes.io/version: 1.5.7
    helm.sh/chart: bytestash-0.1.1
  name: bytestash-data
  namespace: bytestash
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
