apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: bytestash
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bytestash
    app.kubernetes.io/version: 1.5.7
    helm.sh/chart: bytestash-0.1.1
  name: bytestash
  namespace: bytestash
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: bytestash
    app.kubernetes.io/name: bytestash
  type: ClusterIP
