apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: bytestash-jwt-secret
  namespace: bytestash
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQm00YXBtbjY5L1AwUkFO
        MGdqVU42TjN4M2k3RmtiSWkrUUhna0RkOWdjCnY0V3l2Y1hrYlFabXVFbkhoMlVN
        YmR1bmIrYUpiVjFKTnAwd2tUUDh2b2sKLS0tIElnZ2c2ZXlWVE01dE5sU3o3THVm
        bGVYTmNLT1Bibys3QlNmOCtFcTVieGcK8TFa9vvu6nzrDfVnVwzH7KzOmSVkNX3v
        DFSiKTsb1xb2m54wJjArJMBn6TlP5L8WeuApiukEBqQALQGF2hLOwQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-01-02T16:49:01Z"
  mac: ENC[AES256_GCM,data:+NG/4+Tcn5YcSfufUKHcKWF5iG35e6/YvUAuAKe9ROaE6MPtVgNSpyGWg1zpzLhr1coS60hVSNjOLCwoNtHfVLFaxxhk13ySA0vroEhAG7B/zbCC7HORhrR1LMUihpkd16++CrzoIKuj7a5RA8TSSpf18hYKeNw4/SpbjY5i++A=,iv:+2p3rI321ZsGaqzKu1/Q/LhtTA76g7xja1Mkx9ehGtU=,tag:BViZ/JF2j7dBKekUCzMldQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:SEucOFXR4mwrp81os0+tIwOqyPc=,iv:NzRkEP2tbt0dHYwsi4SqzEJwu7xFEJwfe5Br0a/xIlw=,tag:5VeCq4jzgOB5kc1GuIzJcg==,type:str]
      stringData:
        expiry: ENC[AES256_GCM,data:Y/LW,iv:T4N7obIGg5lX1BadHCCtECpFzJEEEE4zASiUPeMw52c=,tag:TSd1u864TPGvKW9VTvji1A==,type:str]
        jwt-key: ENC[AES256_GCM,data:JtK3a9oSdTTvq1uKMKPp5+KNGYqOGSdAW+EXLf7bpL2+aMsw7UlhQrhG2NRfHsEPPMGE2M7ayUKILotJe6lExw==,iv:yl2RrxXeW5eUHzfrgXl/KfcoML6/0mSazE0kRcSujkI=,tag:lMTTc7wlgdxzglXCgoWAww==,type:str]
      type: ENC[AES256_GCM,data:7/XaJeQJ,iv:CQ3jOWZiaatk7lHlOl9bRHVzctfj5Nh8pS2wq9tgtmA=,tag:5UyRA1IrOL6Cyzfhg4OG4Q==,type:str]
