apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: observability
spec:
  dnsNames:
    - grafana.noosphere.uk
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
  secretName: grafana-tls
