apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 80.8.0
    chart: kube-prometheus-stack-80.8.0
    heritage: Helm
    release: kube-prometheus-stack
  name: prometheus-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus-prometheus
    namespace: observability
