apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: kube-prometheus-stack-kube-controller-manager
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 80.8.2
    chart: kube-prometheus-stack-80.8.2
    heritage: Helm
    k8s-app: kube-controller-manager
    release: kube-prometheus-stack
  name: prometheus-kube-controller-manager
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.1.48
      - ip: 192.168.1.59
    ports:
      - name: http-metrics
        port: 10257
        protocol: TCP
