apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: kube-prometheus-stack-kube-proxy
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 80.10.0
    chart: kube-prometheus-stack-80.10.0
    heritage: Helm
    k8s-app: kube-proxy
    release: kube-prometheus-stack
  name: prometheus-kube-proxy
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.1.48
      - ip: 192.168.1.59
    ports:
      - name: http-metrics
        port: 10249
        protocol: TCP
