apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 80.8.2
    chart: kube-prometheus-stack-80.8.2
    heritage: Helm
    release: kube-prometheus-stack
  name: prometheus-alertmanager
  namespace: observability
spec:
  endpoints:
    - enableHttp2: true
      path: /metrics
      port: http-web
    - path: /metrics
      port: reloader-web
  namespaceSelector:
    matchNames:
      - observability
  selector:
    matchLabels:
      app: kube-prometheus-stack-alertmanager
      release: kube-prometheus-stack
      self-monitor: "true"
