apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 80.8.2
    chart: kube-prometheus-stack-80.8.2
    heritage: Helm
    release: kube-prometheus-stack
    self-monitor: "true"
  name: prometheus-alertmanager
  namespace: observability
spec:
  ports:
    - name: http-web
      port: 9093
      protocol: TCP
      targetPort: 9093
    - appProtocol: http
      name: reloader-web
      port: 8080
      targetPort: reloader-web
  selector:
    alertmanager: prometheus-alertmanager
    app.kubernetes.io/name: alertmanager
  sessionAffinity: None
  type: ClusterIP
