apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: karakeep-tls
  namespace: karakeep
spec:
  dnsNames:
    - karakeep.noosphere.uk
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
  secretName: karakeep-tls
