apiVersion: v1
data:
  MEILI_ENV: production
  MEILI_NO_ANALYTICS: "true"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: search-engine
    app.kubernetes.io/instance: karakeep
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: meilisearch
    app.kubernetes.io/part-of: meilisearch
    app.kubernetes.io/version: v1.13.0
    helm.sh/chart: meilisearch-0.12.0
  name: karakeep-meilisearch-environment
  namespace: karakeep
