apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test-success
  labels:
    app.kubernetes.io/instance: karakeep
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: meilisearch
    helm.sh/chart: meilisearch-0.12.0
  name: karakeep-meilisearch-test-connection
  namespace: karakeep
spec:
  containers:
    - args:
        - karakeep-meilisearch:7700
      command:
        - wget
      image: busybox
      name: wget
  restartPolicy: Never
