apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: karakeep
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karakeep
    app.kubernetes.io/service: karakeep-chrome
    app.kubernetes.io/version: 0.27.0
    helm.sh/chart: karakeep-0.27.0
  name: karakeep-chrome
  namespace: karakeep
spec:
  ports:
    - name: http
      port: 9222
      protocol: TCP
      targetPort: 9222
  selector:
    app.kubernetes.io/component: chrome
    app.kubernetes.io/instance: karakeep
    app.kubernetes.io/name: karakeep
  type: ClusterIP
