apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: karakeep-meilisearch-secret
  namespace: karakeep
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMmhyK3h2cmNoeGI1cGlW
        WXZydzlHSFpkcEFyb2hvYXFmcWtIUlNwejA4CmNIS3ZzT05qSWlYUUFPZGY1Nklz
        Y2VpSlV0WGJkZS9wdEwrQURkZkRTTFUKLS0tICtqemNoNzNpQnRaU1dSVlNHUEUv
        V0g5UENSN0htQWovMjRiUmpmTjFJYVEKmQrnZ9WnA5aoplo4QtJVxLTYHjT1bsZG
        wcwmC1yHrfkc1QTDfBeAjPNM8NWAQ1bG9Ex0JolVmbIXPQGicK1i4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-01-02T12:10:04Z"
  mac: ENC[AES256_GCM,data:YPYZW8Sq4dRdSyAdtEpYKSd/a06EpWCqK/OR+OYDZsfkMBkEB9HfOZGAuaUiK5N278ouD+fYoEhfrgAAg9E383rn7kywfsBN9R7ntg0hdA5AiqiwfKofaBN2vsBeV9DO8YaFOewLlzcMc8WMrnTwlkbMob5zQIxoynPw+HM8KoM=,iv:R/VEKz62qU14hsGqJpXRbWJynHmUp/lA/YxsJHp7tlk=,tag:1n2e9xErnnM12gnqI2rvrw==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:9RaNH9mg7wH8mcYca3iPgf38CGLpYiHbdS2O,iv:xO27AMdEy6sYlxr02DkdAiJ4VzPuMk2TkAfWnk/+scA=,tag:e4vy+Nuay6R7Kk95BgMrgw==,type:str]
      stringData:
        MEILI_MASTER_KEY: ENC[AES256_GCM,data:Ii99zDsJSkz47OBg1syxcfQa7yr0YS8yWrabRKGbe+8YyZjZT1Y6Ydni1Pu2Cgrh,iv:XF4ei2m7DCUrrsdcqCmYu5uzOLSGh2fX1Tm4Rzf9hTY=,tag:712bDQUCDfI3O7OIG+Ybyg==,type:str]
      type: ENC[AES256_GCM,data:f7ZFomur,iv:OK+GceUb8yETD9u8UhFimQYjv/+2KJU58h4g/ZoiqB4=,tag:/oiVNWXdP6JrY9cGR98J/g==,type:str]
