apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-traefik
  namespace: argocd
spec:
  destination:
    namespace: ingress-traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./taghmata/manifests/prod/ingress-traefik
    repoURL: https://github.com/apetrovic6/omnissiah.git
    targetRevision: master
  syncPolicy: {}
