apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-secrets
  namespace: argocd
spec:
  destination:
    namespace: sops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./taghmata/manifests/prod/sops-secrets-operator
    repoURL: https://github.com/apetrovic6/omnissiah.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
