apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/version: latest
    helm.sh/chart: csi-driver-nfs-v0.0.0
  name: nfs-csi-resizer-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nfs-external-resizer-role
subjects:
  - kind: ServiceAccount
    name: csi-nfs-controller-sa
    namespace: csi-nfs
