apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/version: latest
    helm.sh/chart: csi-driver-nfs-v0.0.0
  name: csi-nfs-controller
  namespace: csi-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-nfs-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: csi-nfs-controller
        app.kubernetes.io/instance: csi-driver-nfs
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: csi-driver-nfs
        app.kubernetes.io/version: latest
        helm.sh/chart: csi-driver-nfs-v0.0.0
    spec:
      containers:
        - args:
            - -v=2
            - --csi-address=$(ADDRESS)
            - --leader-election
            - --leader-election-namespace=csi-nfs
            - --extra-create-metadata=true
            - --feature-gates=HonorPVReclaimPolicy=true
            - --timeout=1200s
            - --retry-interval-max=30m
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          image: registry.k8s.io/sig-storage/csi-provisioner:v6.1.0
          imagePullPolicy: IfNotPresent
          name: csi-provisioner
          resources:
            limits:
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - args:
            - -csi-address=$(ADDRESS)
            - -v=2
            - -leader-election
            - --leader-election-namespace=csi-nfs
            - -handle-volume-inuse-error=false
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          image: registry.k8s.io/sig-storage/csi-resizer:v2.0.0
          imagePullPolicy: IfNotPresent
          name: csi-resizer
          resources:
            limits:
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - args:
            - --v=2
            - --csi-address=$(ADDRESS)
            - --leader-election-namespace=csi-nfs
            - --leader-election
            - --timeout=1200s
            - --retry-interval-max=30m
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          image: registry.k8s.io/sig-storage/csi-snapshotter:v8.4.0
          imagePullPolicy: IfNotPresent
          name: csi-snapshotter
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --http-endpoint=localhost:29652
            - --v=2
          image: registry.k8s.io/sig-storage/livenessprobe:v2.17.0
          imagePullPolicy: IfNotPresent
          name: liveness-probe
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - args:
            - --v=5
            - --nodeid=$(NODE_ID)
            - --endpoint=$(CSI_ENDPOINT)
            - --drivername=nfs.csi.k8s.io
            - --mount-permissions=0
            - --working-mount-dir=/tmp
            - --default-ondelete-policy=delete
            - --use-tar-command-in-snapshot=false
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          image: gcr.io/k8s-staging-sig-storage/nfsplugin:canary
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              host: localhost
              path: /healthz
              port: 29652
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          name: nfs
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SYS_ADMIN
              drop:
                - ALL
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: pods-mount-dir
            - mountPath: /csi
              name: socket-dir
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: csi-nfs-controller-sa
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/controlplane
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoSchedule
          key: CriticalAddonsOnly
          operator: Exists
      volumes:
        - hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
          name: pods-mount-dir
        - emptyDir: {}
          name: socket-dir
