apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/version: latest
    helm.sh/chart: csi-driver-nfs-v0.0.0
  name: csi-nfs-controller-sa
  namespace: csi-nfs
