allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/version: latest
    helm.sh/chart: csi-driver-nfs-v0.0.0
  name: nfs-csi
parameters:
  server: 192.168.1.61
  share: /volume1/selhosted
provisioner: nfs.csi.k8s.io
reclaimPolicy: retain
volumeBindingMode: Immediate
