apiVersion: v1
data:
  admin-password: WkNFRGVtT2llRjV4b1RkWXQ1SUo1a0JNalRzbVJpYU1ZbWhPOE51Sg==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: admin-secret
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.3.0
    helm.sh/chart: grafana-10.4.0
  name: kube-prometheus-stack-grafana
  namespace: observability
type: Opaque
