apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: grafana-admin-secret
  namespace: observability
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdGdsMWNSemlyTFRtNTNE
        ZUw1bGd0MEJ4dDlxS1prVmpkN3E0N2dBZ1ZBCnRDamlmT2JhSUp0WktYUkxGSWY5
        dkxPanVvRU43THVNampUeUlwQldUWjQKLS0tIHRPUnpvQytOZGQzZGpHMldDK0Rp
        dFZpV3RZbkZQcUtXU051ZjNpa0lTR2MKUhU7LqwAuv99A1xJGp6/aOtlZf0MpIRU
        bA9endhStVa5/YO332flqYqeP6HP641LPHN3Xm+4PEzHFUqoB2kgjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2025-12-28T12:36:50Z"
  mac: ENC[AES256_GCM,data:XH5yaKVWDiNTuH7Ox6/XoRkixRWwjK+Ubj5Yva69SeXhQiMzloBK8f9dXMufq40F3WrPSt3GZuFusk/3rWI6TqPUebzy7XwYQUBjRwpjaWmohPgpVikC9AFXAvpWqGU5Gixyq6yfhd664Fd1UqXrHYsCWNDKv9uMYlN++nuJx1Y=,iv:wiGRggc4A7L12qkp2n+CA5up7hn9GUsR6C4FTz9Zvsg=,tag:VNuNEMPB21n/4dTcw+B9lg==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:amEb//H1Kn2FPTYqaAhs1EewacQ=,iv:zGAYTF2HzAlv42/uRtg6/7KZuUqQ9HtoIGPqzobhN+w=,tag:1eSzFs6RfwE9XysFtD7EAA==,type:str]
      stringData:
        admin-password: ENC[AES256_GCM,data:oGwQ3JrQoqP+NIEeZVI/6fHb3i0=,iv:/WGvXG0LBXNwoP8/8eyKNI+obOnDpGJt0QZ5m577PRU=,tag:lipFbA/X720FgmodC204RA==,type:str]
        admin-user: ENC[AES256_GCM,data:UibhMLk=,iv:QKDw+uO/a8rgWBBwq3DNY399xq9FQr3sgJd8Trv5y7k=,tag:Ak9yBkYCWUOAH5suf+yAhQ==,type:str]
      type: ENC[AES256_GCM,data:LQlnKDfr,iv:I1UOzWuPBgvPpcw5SbzPIOE0dNZ4O7XETT4M5lRFT5A=,tag:CBZ+agxOEP//+6C8nZZiDg==,type:str]
