apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-zitadel
  namespace: zitadel
spec:
  enableSuperuserAccess: true
  imageName: ghcr.io/cloudnative-pg/postgresql:17.7-minimal-trixie
  instances: 2
  monitoring:
    enablePodMonitor: true
  postgresql:
    parameters:
      log_statement: ddl
      max_connections: "200"
      shared_buffers: 1GB
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: longhorn-cnpg-strict-local
  walStorage:
    size: 10Gi
    storageClass: longhorn-cnpg-strict-local
