apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/component: login
    app.kubernetes.io/instance: zitadel
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zitadel-login
    app.kubernetes.io/version: ""
    helm.sh/chart: zitadel-9.13.0
  name: zitadel-login
  namespace: zitadel
spec:
  ingressClassName: traefik
  rules:
    - host: zitadel.noosphere.uk
      http:
        paths:
          - backend:
              service:
                name: zitadel-login
                port:
                  number: 3000
            path: /ui/v2/login
            pathType: Prefix
