apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  name: zitadel-ip-root
  namespace: zitadel
spec:
  ingressClassName: traefik
  rules:
    - host: zitadel.noosphere.uk
      http:
        paths:
          - backend:
              service:
                name: zitadel-service
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - zitadel.noosphere.uk
      secretName: zitadel-tls
