apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
  labels:
    app.kubernetes.io/instance: zitadel
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zitadel
    app.kubernetes.io/version: ""
    helm.sh/chart: zitadel-9.13.0
  name: zitadel
  namespace: zitadel
spec:
  ports:
    - appProtocol: kubernetes.io/h2c
      name: http2-server
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/component: start
    app.kubernetes.io/instance: zitadel
    app.kubernetes.io/name: zitadel
  type: ClusterIP
