apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: login
    app.kubernetes.io/instance: zitadel
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zitadel-login
    app.kubernetes.io/version: ""
    helm.sh/chart: zitadel-9.13.0
  name: zitadel-login
  namespace: zitadel
spec:
  ports:
    - appProtocol: kubernetes.io/http
      name: http-server
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/component: login
    app.kubernetes.io/instance: zitadel
    app.kubernetes.io/name: zitadel-login
  type: ClusterIP
