apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: start
    app.kubernetes.io/instance: zitadel
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zitadel
    app.kubernetes.io/version: ""
    helm.sh/chart: zitadel-9.13.0
  name: zitadel
spec:
  endpoints:
    - honorLabels: false
      honorTimestamps: true
      path: /debug/metrics
      port: http2-server
  jobLabel: zitadel
  namespaceSelector:
    matchNames:
      - zitadel
  selector:
    matchLabels:
      app.kubernetes.io/instance: zitadel
      app.kubernetes.io/name: zitadel
