apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: master-key-secret
  namespace: zitadel
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMTRRNHdITXVJb2Q4UjMx
        MEt0YWpHMmEvNjZ3dEw1eUEwR21xZGlZNUJRCkk3TjNxMVg5TVhzZ3NQUGVrMElj
        VVdlblhMa0VvbWdQalJKQUlJYmxtOHMKLS0tIFExeWdtTDBDbENRdkxPamx1eEpW
        enZDbUVsTXBCbmFlQnl2Y2xLVmlzUU0KkkB8bszGIDtAXxTlQc/aFqZ3+HCxRaH7
        26WN7HQ9uDtILt5R3CXnXRlwjBouA1kFyvQQNN/dpj6UfvqcY0aotQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2025-12-27T16:22:46Z"
  mac: ENC[AES256_GCM,data:QJ3zaGyhsu74CaaEADBFsPpdrS2RElwQ61y54pezCiGXzTcZIFqgwmlGuIC/wKkgzSoh89HFoTjQxYI9RuM4/eDzbp1N72ImbDjUdRB+3iwbHaItQU0Xz2u/JDBT0c7rC4N4ZAjQ2FNtEkafgLvr/cx73G+3+8FYK9rOz+jiens=,iv:U1q9siD+tmWe0c5D9jnFKwWM/hfik6oOukBSNaZGGwI=,tag:vGtgW+ybKnL0njJjZCp+Ow==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:ZpiqL8WCeGT+Dy2w+npIHe0=,iv:tBg1LeEfJQJ8l3BTSSdMa9q8hw0T4afRZaEB7gZSvZ0=,tag:VkihmWYHAjQJSkufOJXyeg==,type:str]
      stringData:
        masterkey: ENC[AES256_GCM,data:j6eh0+A/REicMbJ809O7Hj8iF/9OPEA54xdKHv/2U7g=,iv:fWjbCrQ7Fwbh4ujTUgqyZFJkoFYPfSmoXzL9tPg8zx8=,tag:galzx+oXvhnEkvrbCDBv+g==,type:str]
      type: ENC[AES256_GCM,data:rU73iT4f,iv:Zbzqz1F5JIMi966GRqqutRJWnIvLa3Y8oE2G0AfbEqA=,tag:/9YCaab7KpjKk3qbrP/mYA==,type:str]
