apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: master-key-secret
  namespace: zitadel
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbUo4eGxzZWtqQzdxL2w4
        S3E2cUdORWp2Y2JVQUFYeDc5QW04ZjhsSENBCmpqWHRNTkc0RE5ZYUgwT2hjYi9O
        Wm5KdkVZUFZ1eUJpYUVyWjkzcjhMUXcKLS0tIHhYZXhSRGtyVktCS0RCY1RHdXhs
        cG5rcGZnclBSbEdoSHJSTEE3eVk2MU0KsTzx5u6g1sa5zoU6jtdLWoXlezVzD9Jj
        AosingXS6v4e/NxEHmC4UUlIa0mJ18qpGt7Wjbxm4bVWaNamBybcnA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2025-12-27T15:19:59Z"
  mac: ENC[AES256_GCM,data:FFqaz32HeXSLYjK0zoSNFG8hk+QEXmp47r66rUj+izlxdcKkzWXGqQVRuFOAnw7YfnwNoKG3cBRuDAIAnxRRX0IQ0VCj6uSoacyUY0Ox64Lyv0+w2TcKn62nr35hbfBifUPsdEhAyUGxHaZ2030V5AF54xamCOYxX0360T0E5OU=,iv:94GtW00pplg+tONruRl4M2XrkACw/8qrx/3+CF+9zWo=,tag:z71ac7US1JQWDVy3czHzPg==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:vrbCJZ9xvHt9D8Z/PxJ1pcg=,iv:AqmkyXiQJL2Kz7fYx2FPyLV43lWPcUeQeskRzLn5OWQ=,tag:ikorZ/CsNrcONSEjfR671A==,type:str]
      stringData:
        masterKey: ENC[AES256_GCM,data:JuGxxDeWr5qJ99Lq5VZ5jN+coDz6kl3+aINBZ053MuU=,iv:wm0TqX6EVBLkts2kyfjvN+jg/Hvfk+RW3TcdO2+rOq4=,tag:jssDkeOfB6b0MPTleKvAhA==,type:str]
      type: ENC[AES256_GCM,data:pnxVdDbJ,iv:KUkr+tr1gl+qdIdcgBTfPYm9ehagVTgPc3BxlI61OSA=,tag:9g+8qN5iG1cyd8KSecOmlQ==,type:str]
