apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: garage-ui-tls
  namespace: garage
spec:
  dnsNames:
    - ui.garage.noosphere.uk
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
  secretName: garage-ui-tls
