apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: garage-ui-jwt-token-secret
  namespace: garage
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMFYzLy9kRW16VXFzTW16
        WGdGVWVzL0U3OTZuNDhMOUJXazV3YS9Fa3hVCjBQZ1NKaUUxV1ZHQjVhMVlQb2hl
        a0xNNWZFaWZFR2JDN0h5dWZVTTV0WVUKLS0tIGloTm8zTlkyMjFUTVl0NSs1VXZi
        dVcvVll6Qy9GakRDekZlYWRjOXdwS1EKMdG1pZ3ivJfZYWPDhTwDNTWjep4DWNd2
        sNnU54ynMFweV6IxGoW4nMTg0bI5HYarbf72KCZqOOSJPEfHk0ftGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2025-12-31T17:25:18Z"
  mac: ENC[AES256_GCM,data:lQdyAsMJFESYXza+h8bRqQRCDyLlYmycSTQXJHyGQEu8tfX0TxY782aLdPDFSZCDZfwLdOiw4wjwSNWMeo3BI0ybFT5wokt1/DjMkthESop6yTiQAClFJ0eXq3yWSfn36uqpLFZOac0JafSmEw9ITv5p7s2Yrnzl49Oriwe0ld8=,iv:cCVwheFyhfx5cFXby22TSkUMu4BJFpY3UBiKiy8pas8=,tag:2WALVppkeNGv+LaJN2RiEw==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:aIPuXO1ujrXmcybmcxBIaxj5lOM0KwaNEJQ=,iv:t2ASQC340UkfdcYpMtt+8ErUMlzhE1FJb8o23whiIWY=,tag:0Tb8i+yaHQa1Lr6yY7U3Mg==,type:str]
      stringData:
        jwt-key.pem: ENC[AES256_GCM,data:TZRyn1o6PVvDENXUUF0KqM5LK2aD4KnCXN4c+86H/Vjq7LT4B0ssjdxyJj+w2gpYm90mEe5RFStrmtxUL6nVI5IfucgQG0djRUI91odmpt2VWspzFXdJsOLBvUabOQpT6HaPvFNhqt8J6mloKHNBpPE6Ior/CNr/3dfA5uTLPad3vVC3qf8Q2msQHazPSHCdWWwXDvkGrDJDkUKEpsIikw==,iv:LItiBiQxtODU4MVgyt4TPDjUDY8m/psrGUh4NrmvJsM=,tag:OJmye9he3/uhGje+IZ4OaA==,type:str]
      type: ENC[AES256_GCM,data:/C8kUiGB,iv:VGNmDK98+FHwSyaslxj4vZz1yocT2a6PCYKGIhzoXXQ=,tag:2gYjUwgA4tn1Wk59MkMb/g==,type:str]
