apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: garage-ui-jwt-token-secret
  namespace: garage
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcW53cnVXNlV0Q3kyRHFW
        cjZXM1ZwSmNkOHJTQ21DVDlEUDJBTituRUQ4CjllNjA1MFRwUythY2dTWWdsWDN0
        cXZDK0tYcjJjK09DZjJhb2UxV21OcTQKLS0tIG1LeXBQbGNjK1lJakJxcFRabVp0
        TnZKVXJzR1J0R0RMYmN3Z1BGNHdnMncKpzk8bRLT4jskPFzHAFz3V6MQsikjcPlU
        VjkNbrGAEQ7XTsN+Hz/n06RHhRnFMQvEdyBBTU4nn35yaQ32BVPLHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2025-12-31T17:34:00Z"
  mac: ENC[AES256_GCM,data:SiNaBLfWkUFe3VEFho3KmGcTI+OVynpHb0scvfxd+icJNtnQ0aEoOvdobrc/kvIDxE3JjukNd99/WRaV4qMg2SQNKEjFnO1gqpvPdY75GzISga4In0B+ZnpXJfb8R0LwYUghxgBTxdwOdLw8a7azsrSeeUB/A+6YZWwutCj/5hE=,iv:ED73DAMbf8IdekVqXuByMdgGGj4RPQMHGR6MBQR9Rho=,tag:Njf23Er4yXGFqs3sFDwlxQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:pIj4D0DUJoCYu8SVlJlGgExOAg8grSX1WJw=,iv:okm98NJiVWiEHhluluSZqvojri0TbO7wT2uIzeMibPg=,tag:vU2jhz9ZAeILjXVrnniKgQ==,type:str]
      stringData:
        jwt-key.pem: ENC[AES256_GCM,data:DqcF2ri4tHs1TPwpp7F3aeDAbGCKia0I6voU6Zfz5bdoZ3vivtRLwT13jkPNdtkes+NyIlHisyAnLMEOZo5DPBDiyV0SS+/d5PyfGPDMY6ssVtKGWboxe/TrbWEFBvEJkuGi1vWp/mGUA8RmHugbcfS0R2PyDA==,iv:AkcKobpK/ayfCgS0uOUNRVi7kkQyjNyUq3jyX9Eh9F8=,tag:LcvuaqPFRNk7y4iuKg9LNA==,type:str]
      type: ENC[AES256_GCM,data:0lb46FMw,iv:cDDB42EOpLBrSzSIkEFkeQ4jy22TRi49x056/tQ2tic=,tag:+MlpvbNLCHw1FPgdxQBrTQ==,type:str]
