apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: garage-ui-jwt-token-secret
  namespace: garage
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNmMwUzBKZ2Q1ajZMNi96
        UHlJdytLcXFlUGp0dmNvQTUzKzVleXBTWTBRCkVROEtoczJrVGlvNUFNaS9jTExh
        VmF5YTlidUJYb0NRbEg3K0lrNlhrZmsKLS0tIGRqRnVCR0xtc2NMNGZsLzBHQnhs
        MFdUYTluTHBhWGpzNkI3ZjhFY1hGTGsKotIF1/AqvnisUH7QwNMLmAtzWLEqOCos
        GZTFT5Ouz5IHu7nNREp08qaUXEk1C+FaWIcNRs7jAzB0cX7V5X6X/Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2025-12-31T17:45:05Z"
  mac: ENC[AES256_GCM,data:tPuAAZbC2julq4jK3J3yKl5IIHG4tsNuATZ9r2RIo40e8MxoFeKf5JVS+Css1VjI315ITpY5X1Fsu5FzWDtobCZQJ5YlF54yaPQGkHcBgMGC5ElcsAORbvdGx83NbR+0I6Y0KCszUIzO0tJuGd0lNw/zbF9dAVfOy+9Ikgg3LWQ=,iv:rqKS8c19lLZyHgHjEaoevJfNhBBKf67q8SEkWOslWmY=,tag:FfcYul5ZMyaWyhgeFI5OEw==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:IHaX/CdR9WkJj7+8JnDjT0fRO8sTuHft5cY=,iv:qGh8I52qzmiYcagOdjMwxC/DWprBpnqEH2764SzguCU=,tag:swLlOSGln0y6Uq4eTzZfJQ==,type:str]
      stringData:
        jwt-key.pem: ENC[AES256_GCM,data:Qud2ACt2LZ4QQPft7MPCNIr6+GD+HyE5g3r/ff22LPRBjvREcSnNts498GhIWOyWkaVToi5VTPGTkY9b7MYE9ZCJeWvziYn7e0hjKNfvhFbDJtvFONeG94yuP39SW24x2A9DTIzDbXNCe6t1EEavJx8MSVu9yg==,iv:jw0KAR7akYJJ7oT7tl4I8jXdbK+VCxOJF4sKWYj1DIo=,tag:KBL7OCBNmm+o/An+Tus8iA==,type:str]
      type: ENC[AES256_GCM,data:FVrdsJlH,iv:yjLvBGH38VlGYeu8DUzL8CUKd+4O8uvhYHTwYh9jhwY=,tag:1OASInO+qhKCh+3CKcgXRQ==,type:str]
