apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: garage-admin-token
  namespace: garage
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVm5WWUdLQjNYWWM3NE9C
        cVo1ZHpTNW01YmpYdzM3cmhLWjFydUVCMTBVCmhMNjhrRDdrM0phdm9IYk9EQkNV
        MUF1dzA5NDFOZWZnWUZkbUc2VFBReFUKLS0tIFJDcUcvcTBMQXN3RkNGcDNsOFZ6
        cDFQSFdxTnpjQlNMSjFVQWpsR3Z4T1kKQX4oLZIZ2IUdn8Nbly6UBRwp/XYA1Bzm
        VhMC9jFo7aex9D3yIReySoMOZWruub5+Qp1TgW6Kgr9F/NWxtRJpmA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2025-12-31T09:45:51Z"
  mac: ENC[AES256_GCM,data:SfH/fHvTBO16zizRZQ5cjmQEuroObQUCv9hLIMJtnqoqn3ox+i1QPOWDQZ/ayPhsaeyBlnWb7LVrHE2PKlMrAZy+TO6IK4z28ScyGXwAecNnrwuqibgbhJiX3sS+9u+YrdkVnfMNbBSyYxMAauss0aWIzVvqJTlx9sdz8v/gmqg=,iv:toxCB0TS9+90KcxPSb/qZ8ujW8lYBpS3IR+YMS+SoA8=,tag:ArKB12lUGSc4TIswIBBh9Q==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:RgEUKnQRemGX4BgpE/AAay7P,iv:dc1HjejLmna+mHKHoK8HLIjECdhhiXrdlgUK9I64UDw=,tag:I8ZgLBxJmipY8PMUvyuJ5A==,type:str]
      stringData:
        admin-token: ENC[AES256_GCM,data:QwinCqPTeVO2Xz2ZahGb5RlPEjKVAJTs,iv:ny1Y74+VPbyU1Cwet6fYtZI5EiVQkKF6b5oscCVYAcA=,tag:/UVpUwu2RLDme231O5WEGQ==,type:str]
      type: ENC[AES256_GCM,data:hdYsbCLc,iv:+o0DJlfsuuED2XfV9omHtnUICAVEDoEBNLiWNeoYxhg=,tag:aPShG10gMYop5u0S7fJxng==,type:str]
