apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: garage-ui-jwt-token-secret
  namespace: garage
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDY05CYzREQUtuWWwycy9C
        aURoN2dnSEMzd3drWGp1TFRLbCttWEFpeGxjCmpuNzIvUEwxTDA0L1k1UjkraC9G
        OVVYcDZqMDFnNWNEQ0tEdjBQRldKdEEKLS0tICtpUHU0bUZBZGpLUi9NQmozTy9R
        UThVNXhjcm15Q3BtVStacjdCZm0ySVEKyPZMkoywuCM4D3bd8+AddpIiJHHalJ03
        5azgGktq7ZshZ2ra7h93Eb+D/AQ4oG1/xOyMaXPP5XU+81m6OWvlvA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2025-12-31T17:08:27Z"
  mac: ENC[AES256_GCM,data:S3NRlO1Y6mdXYHssEAWMGZcBCMW49/9XKVWl0Xc1hNun0koxvGGJKFcYdFGM0INn64eZk5L9nLP9jFgs15RGFCc1vWBDPbbi1nlx6fpoCn0+UcP2EUxkFERVb08ljZqT03T/re8Zfdicw9xPQOuTm3m9IQOTsHs19PoKeZfAcHQ=,iv:tNjdfrNNIxI11qP7/zeKr6t2LsNmGlfq8Vg3rZCBjmY=,tag:n2WsEZlsCZyrX67YcUjppQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:KOmCkcB+6tE8jixB0OTw7pJzBSKZuP6Mg5g=,iv:aGl8pNDj1JnxwyDblOBtaBG/D09XrKGWyLiw0xDKmKE=,tag:MwEoH+KFfifqL9mH4VXc4g==,type:str]
      stringData:
        jwt-key.pem: ENC[AES256_GCM,data:AX5dgEV7VEgOYfCGXxLfPltgz+jSFDTuHpbrB5L2KmhqZX3sQziN6ADZnolz9DjPFa2qptZ/GpzJcbXvXaTtwr2D/JKETiLZ/LixgWEQ+BA8bVNOlUFJ3BNUDRXDnJ9SpTEeO7/GfBS9OEcudtipl2gvdVYEhw==,iv:2De7FKsAM495LBMYL5UVhGQ/4qubkperSsLiTLpY4OM=,tag:BWepPJlj36OccCq0B7SwOw==,type:str]
      type: ENC[AES256_GCM,data:hhGmS09t,iv:X32Cfm8Y+t6C8bJCnlrsNS3/ixqAMkNYDUeD23vbDLw=,tag:SBiPFl5gfXKuSIVds0/mrw==,type:str]
