apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alloy-tls
  namespace: observability
spec:
  dnsNames:
    - alloy.noosphere.uk
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
  secretName: alloy-tls
