apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alloy-operator
    app.kubernetes.io/version: 1.5.1
    helm.sh/chart: alloy-operator-0.3.15
  name: alloy-alloy-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alloy-alloy-operator
subjects:
  - kind: ServiceAccount
    name: alloy-alloy-operator
    namespace: alloy
