apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alloy-operator
    app.kubernetes.io/version: 1.5.1
    helm.sh/chart: alloy-operator-0.3.15
  name: alloy-alloy-operator
  namespace: alloy
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: http
    - name: metrics
      port: 8082
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/name: alloy-operator
  type: ClusterIP
