apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: excalidraw-tls
  namespace: excalidraw
spec:
  dnsNames:
    - excalidraw.noosphere.uk
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
  secretName: excalidraw-tls
