apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seerr
  namespace: argocd
spec:
  destination:
    namespace: seerr
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./modules/noosphere/taghmata/nixidy/manifests/prod/seerr
    repoURL: https://github.com/apetrovic6/omnissiah.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
