apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls
  namespace: harbor
spec:
  dnsNames:
    - harbor.noosphere.uk
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
  privateKey:
    rotationPolicy: Always
  secretName: harbor-tls
