apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: harbor-registry-http-secret
  namespace: harbor
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISU1wbWh6RXBaT251NEYz
        L2FOdGdhRElMK1BTVExUbUdJQTI1SDdmdGhzCmNtNlhVNDFJd3hNZ1BoellKVnd2
        eUlWUXVhMUQ2UnNmOUNoUHluN0VqMjgKLS0tIG1iUDRFcktCVVZ3eEhkdkdLWUUy
        TjhKdUV4TmhtWVNqcC8vTnQ0T0haaVkKaoewysSUMbMArj12A9OzckAN8wTnFteh
        UjBRaQlv9WXIUZeXCmdLQ0NNK9u0hpp3OXMMJMNFe7n2w2ztQQhzsg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-01-03T13:46:51Z"
  mac: ENC[AES256_GCM,data:xrndXcrmN6xbd/LrQ2HwL3caa2PuUA7jZsZXTtLbLwcAOmf1JPecZbOYTxmRDj84bSBk+YttmdYqDK9rDFZ7MloGEPK3Xm4HTXt1ZCNBxKtf+9csLl6ZBHqfSPsh+R8+xW0i4aJclQYntFEp7Ki7G013KVqFoOFnAFN/6mMk4JM=,iv:P6voTImCuZzOjhpFgFoBqt6oPr60Oe6V0ejzHpIWvNM=,tag:8fTfMruWgdJdmZW6vnIA5w==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:6rFnv7ddrvyBeJfuUxKdQ5Pz2/7lGufJ3383,iv:2qKwayhy3IJm7yCUhkHXx6zbYry132Z99obtaGZT9bM=,tag:1qC5zBiqb0W6Tc1SJOw35w==,type:str]
      stringData:
        REGISTRY_HTTP_SECRET: ENC[AES256_GCM,data:jV/x+5W6lIsDt3+jVCNaYA==,iv:5zo7TFG5cDh8D0HBju6ulzPPTuypFbFdXpx6q4kkzFE=,tag:yMM6Okg3z5S3LJu525nebw==,type:str]
      type: ENC[AES256_GCM,data:NCtg484k,iv:28TMLcAkhzoNovTR1XdbpAa+z91v1wQzpK1J3nIUHD4=,tag:IT6aEEZoQaysGX6z1VmbMA==,type:str]
