apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: harbor-registry-credentials-secret
  namespace: harbor
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWGNkWm5pZXUvOUFpN2xk
        TXJZTzFYQzN5N0FxWnNmc1Bnd0JvR2pISGx3Cms3dVlKQXhlZVM0cHNkNjF3Q1pC
        cWZLOElFcmRlb2N1RUxKenF5d1RhR2cKLS0tIFRpSkMxRER3alc3cEhxNUdqS2V4
        TGtFbk1YcHNMQjNoRWpmREdYS2JZR1UKv1QjUUJJFyc74BnQl5inEVEwXbtCNMDc
        /9uo0XcYhb5jggQE0exOKK9yYUWbh7qYhpaQopdO89k70N2VQaRhsQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-01-03T14:26:04Z"
  mac: ENC[AES256_GCM,data:FAkvcGxLzUFCaFGuUZpmbw0VnY/gDnR/qXh+0Ll0UP7GEmKw5QQhDI+QH+hdVrTesyvbAHaKTnrFLrg4KDv5rqX0YiZUYb5gVIU13YkaDVQKxtIDQOdwq86Pgb/PFR4MrqmwrJQarxAa0BUDg6hQZzCSXe3BjaZNnWbVImtLuHw=,iv:bwLv/IQ0HYjMyPXS61iXMwIWV0mBUoVHp+UdPP5fs8I=,tag:UkJT/LhvU8rqyMHmRGeOMA==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:T05yHiCopBQ1AiF9wOTFK5AKDbWeEQRsBslPdX45h2cbRA==,iv:7JBEV00I0NFXP/tShsRvecYq+3hVp7NLdiF01VG6m0k=,tag:MUOf4ca95wyHJJFytfxXLQ==,type:str]
      stringData:
        REGISTRY_HTPASSWD: ENC[AES256_GCM,data:SGHVt3maC3SPzNfN5Wyughe8U17kpdod/gkzcAa8JMHSIXcjZkIDck8mPEKsCdBn5Np8JiWobXTbEZG51DU+ipaCdg==,iv:+bvWqW5txLlYG2/xd8c7jDFWqCNg7Qa5lwDsBV3HaGo=,tag:15cwFGqIsdx95VGPiA78SQ==,type:str]
        REGISTRY_PASSWD: ENC[AES256_GCM,data:dIEeV7tMqzKCA+6+h/FYhEVmZ/X4aQQNJQU1oMA+1lE=,iv:tV8b4onsxcGvX6/T4D1/3XJql0fy562Ag1mjB1W3vp8=,tag:uDZDFx2UYFPdh1uj996P6w==,type:str]
      type: ENC[AES256_GCM,data:mpMoYQa1,iv:VCkaHQxESIm8ahYSS09+b1LmamMClYHFoflP/RbPO/o=,tag:CURld4XppyoxWldTmftmvQ==,type:str]
