apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: harbor-admin-password-secret
  namespace: harbor
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSUw4RDc1VWdSQ0VydzFt
        K2loWTdnQmFFSVVUZEpyUjZneENJQ3pGR3k4CmZXaE5sK1pYVk9WN2lmb3JRTXVl
        ajhLazh1MEdTbS85T3JPK1YrYzlrc1kKLS0tIHc4MTNRaFljY3pETEx3VCs2Kzg3
        T29yU2lJZnJtUTVKbDZ3cUk5RllMaEkKiupldYWLhCf9Q/eAEFPOTcPCo1JB9i0F
        b1y59ex24MgdKhv96gOzIu9HD2xljttpNsolNDRlHyXZaqxuQr166w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-01-03T10:18:41Z"
  mac: ENC[AES256_GCM,data:q2K8puEBeIEbrT8pEgqiFfpWrdywkh0UOZH3Ch6vn90nC2vNwFOI067i3foZ8Q4U1R1H3M0uHwguzS0eAOQeWmVPbQjZvcR7Kr3aD0bJixwC/0AqyqEEt353ssMXeu0qH1c8g/RjdZzWXjon045AnCidea0TZuvRO7Qr89RvJhg=,iv:IAkIa4Gqec+xCwrk5Qds6jroTamxz4ItEPB41psje8g=,tag:fgiGvZCeKKvDMom0uc48oQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:VQJidPBLmycP9r6TjL4eRygmuszyAKwem/bCZg==,iv:WY+dxx7vzJT88drs+dBvtLVLZmrAV9Vz1jxvwgVByzQ=,tag:yVyDime2n9c5nWcRRXEAEA==,type:str]
      stringData:
        HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:n/RvaDCNMXzCyA3ZLupTufLprABThgB5k2VJMR1gcAc=,iv:cXWHJNwD95AwCXyUnJ5V9/fKJbNZIswR38poI47JaA4=,tag:hojzg1EbZ/UtefD3umGC9Q==,type:str]
      type: ENC[AES256_GCM,data:ZzU9gjFm,iv:3LhOxu0L0tbxyGUx1jenFcP1S+/cMsvJz8bBr9R1bMc=,tag:cKhBvdtTbf4qAiLTWMWq2A==,type:str]
