apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: seerr
  name: seerr-deployment
  namespace: yarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seerr
  template:
    metadata:
      labels:
        app: seerr
    spec:
      containers:
        - env:
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: pg-yarr-rw
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: pg-seerr-password
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pg-seerr-password
            - name: DB_NAME
              value: seerr
          image: fallenbagel/jellyseerr:2.7.3
          name: jellyserr
          ports:
            - containerPort: 5055
          volumeMounts:
            - mountPath: /app/config
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: seerr-pvc
